package com.event.driven.stock.service.enums;

public enum EventType {

    STOCK_RESERVATION_CREATED,
    STOCK_RESERVATION_CONFIRMED,
    STOCK_RESERVATION_RELEASED,
    STOCK_RESERVATION_FAILED,
    STOCK_ADDED,
    LOW_STOCK,
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
}
